name: InvestorIndicators
on: push
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate metrics report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BEA_API_KEY: ${{ secrets.BEA_API_KEY }}
        run: |
          # Workflow runners
          # Install requirements
          pip install -r requirements.txt
          # Indicators
          python src/buffett_indicator.py